CREATE TABLE series (
  id INTEGER PRIMARY KEY,
  title TEXT,
  sub-genre TEXT,
);

CREATE TABLE sub-genre (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE authors (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT, year INTEGER, )